<?php
//Global define
DEFINE('BASE_URL', 'http://localhost/Template_MVC/');
DEFINE('APP_TITLE', '');
DEFINE('APP_VERSION', '');
DEFINE('LOG_DIRECTORY', DIRECTORY_SEPARATOR.'logs'.DIRECTORY_SEPARATOR);
DEFINE('WEBMASTER_ADDRESS', '');
//DB define
DEFINE('USING_A_DB', FALSE); //SET TO TRUE IF YOU USE A DB WITH THE FOLLOWING INFO
DEFINE('DBNAME', '');
DEFINE('DBHOST', '');
DEFINE('DBTYPE', 'mysql');
DEFINE('DBPORT', '3306');
DEFINE('DBUSER', '');
DEFINE('DBPASSWORD', '');

?>